name: ecocash
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  test: ^1.19.2


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
